# services:  
#   frontend: #Define the client service so we can run it in an isolated environment.
#     stdin_open: true
#     build:
#       context: .
#       dockerfile: Dockerfile #The client service requires a docker file to be specified. 
#     ports:
#       - "9000:9000" #Next, we map the port 9000 to Docker. 
#     volumes:
#     #   # - "/app/node_modules"
#       - ./src/:/app/frontend/src:ro 