# Generated by Django 4.2.11 on 2024-06-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', related_query_name='images', to='products.shoe')),
            ],
            options={
                'verbose_name_plural': 'Shoe Images',
            },
        ),
    ]
