# Generated by Django 4.2.11 on 2024-06-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shoeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
    ]
