# Generated by Django 4.2.11 on 2024-06-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_remove_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoeimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sicreator', related_query_name='sicreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoeimage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoeimage',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simodifier', related_query_name='simodifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
