name: Deploy to Railway

on:
  push:
    branches:
      - main  # Adjust to your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | bash
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
    
      - name: Log in to Railway
        run: railway login --token ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway
        run: railway up --detach
