name: frontend-testing
run-name: Running Tests For Frontend
on: 
  push:
    branches:
     - main
  pull_request:
    branches:
    - main
jobs:
  components-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies, build and test
        run: npm install 
        working-directory: frontend

      - name: Run Tests
        run: npm test
        working-directory: frontend

